PyTorch 00

In [178]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Pytorch Version: " + torch.__version__)

Pytorch Version: 1.13.1


In [3]:
# scalar tensor
scalar = torch.tensor(7)
scalar

scalar.ndim #dimension


0

In [4]:
# Vector 
vector = torch.tensor([7.7])
print(vector)
print(vector.ndim)


tensor([7.7000])
1


In [5]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)

tensor([[ 7,  8],
        [ 9, 10]])
2


In [6]:
MATRIX[1]

tensor([ 9, 10])

In [7]:
MATRIX.shape

torch.Size([2, 2])

In [8]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 1],
                       [1, 1, 0],
                       [1, 1, 2]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 1],
         [1, 1, 0],
         [1, 1, 2]]])
3
torch.Size([1, 3, 3])


Creating Tensors

In [9]:
#Random Tensor
#Create a random tensor

#provide size
random_tensor = torch.rand(3, 7)
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor)


2
torch.Size([3, 7])
tensor([[0.1825, 0.7934, 0.9068, 0.3097, 0.9184, 0.7912, 0.9904],
        [0.5270, 0.7834, 0.4327, 0.0118, 0.0458, 0.4654, 0.2876],
        [0.1015, 0.4753, 0.9560, 0.3875, 0.1365, 0.8439, 0.6020]])


In [10]:
# Random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels


Creating Random Tensor

In [16]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
oneTensor = torch.ones(size=(3,4))
oneTensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
nineRange = torch.arange(0,10)

Tensors Like

In [31]:
#Creatign Zeros-like
ten_zeros = torch.zeros_like(input=nineRange)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [39]:
#Flot 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                                dtype=None, # Data type
                                device="cpu", # What device is your tensor on
                                requires_grad=False) # Whether or not to track gradients with tensor
float_32_tensor


tensor([3., 6., 9.])

In [42]:
float_16_tensor = float_32_tensor.type(torch.float16)  # Casting to lower precision

In [48]:
#Multiplication accorss data types?
print(float_32_tensor * float_16_tensor)



tensor([ 9., 36., 81.])


In [49]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

### Getting information from Tensors

1. Tensors not right Data Type
2. Tensors not right shape
3. Tensors not on right device - For local AMD GPU machine, just use "cpu"  use "cuda" if NVIDIA Gpu used


In [52]:
# Find out details about some tensor
print(int_32_tensor)
print(f"Datatype of tensor:  {int_32_tensor.shape}")
print(f"Device tensor is on:  {int_32_tensor.device}")

tensor([3, 6, 9])
Datatype of tensor:  torch.Size([3])
Device tensor is on:  cpu


### Manipulating and Operating with tensors

Tensor Operations: 
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matric Mulitplication

In [60]:
# Tensor 1
tensor1 = torch.tensor([1, 2, 3])
tensor1 + 10  # adds 10 to each

tensor([11, 12, 13])

In [61]:
#Multiplication:    WORKS ELEMENT WISE
tensor1 * 10

tensor([10, 20, 30])

In [62]:
tensor1 - 10

tensor([-9, -8, -7])

### Matrix Multiplication

Two main ways of performing multiplication in machine learning and deep learning
1. Matrix Multiplication (dot product)
2. Element Wise multiplication


In [113]:
# Element Wise: 
print(tensor1, "*", tensor1)
print(f"EqualsL {tensor1 * tensor1}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
EqualsL tensor([1, 4, 9])


In [114]:
%%time
# Matrix Multiplication:  (DOT PRODUCT)
print(tensor1, "dot", tensor1)
print(torch.matmul(tensor1, int_32_tensor))

tensor([1, 2, 3]) dot tensor([1, 2, 3])
tensor(42)
Wall time: 2 ms


In [115]:
#Tensors
tensor_A = torch.tensor([[1, 2],
                        [3, 6],
                        [8, 2]])
tensor_B = torch.tensor([[0, 1],
                        [4, 9],
                        [1, 3]])
#torch.mm is analagous to matmul
#torch.matmul(tensor_A, tensor_B)
tensor_BT = tensor_B.T
print(tensor_BT.shape)

# To fix shape issues, use transpose!
torch.matmul(tensor_A, tensor_BT)

torch.Size([2, 3])


tensor([[ 2, 22,  7],
        [ 6, 66, 21],
        [ 2, 50, 14]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [133]:
# Create a tensor
x = torch.arange(1,100,2.5)
x, x.dtype

(tensor([ 1.0000,  3.5000,  6.0000,  8.5000, 11.0000, 13.5000, 16.0000, 18.5000,
         21.0000, 23.5000, 26.0000, 28.5000, 31.0000, 33.5000, 36.0000, 38.5000,
         41.0000, 43.5000, 46.0000, 48.5000, 51.0000, 53.5000, 56.0000, 58.5000,
         61.0000, 63.5000, 66.0000, 68.5000, 71.0000, 73.5000, 76.0000, 78.5000,
         81.0000, 83.5000, 86.0000, 88.5000, 91.0000, 93.5000, 96.0000, 98.5000]),
 torch.float32)

In [134]:
#Find the min and max
print("Min: " + str(torch.min(x)))
print("Min: " + str(torch.max(x)))
x, x.dtype



Min: tensor(1.)
Min: tensor(98.5000)


(tensor([ 1.0000,  3.5000,  6.0000,  8.5000, 11.0000, 13.5000, 16.0000, 18.5000,
         21.0000, 23.5000, 26.0000, 28.5000, 31.0000, 33.5000, 36.0000, 38.5000,
         41.0000, 43.5000, 46.0000, 48.5000, 51.0000, 53.5000, 56.0000, 58.5000,
         61.0000, 63.5000, 66.0000, 68.5000, 71.0000, 73.5000, 76.0000, 78.5000,
         81.0000, 83.5000, 86.0000, 88.5000, 91.0000, 93.5000, 96.0000, 98.5000]),
 torch.float32)

In [149]:
#Find Mean - torch.mean() function will require a tensor of float32 datatype!
torch.mean(x.type(torch.float32))

tensor(49.7500)

## Finding Positional min and max

In [150]:
#reuse tensor x
x

tensor([ 1.0000,  3.5000,  6.0000,  8.5000, 11.0000, 13.5000, 16.0000, 18.5000,
        21.0000, 23.5000, 26.0000, 28.5000, 31.0000, 33.5000, 36.0000, 38.5000,
        41.0000, 43.5000, 46.0000, 48.5000, 51.0000, 53.5000, 56.0000, 58.5000,
        61.0000, 63.5000, 66.0000, 68.5000, 71.0000, 73.5000, 76.0000, 78.5000,
        81.0000, 83.5000, 86.0000, 88.5000, 91.0000, 93.5000, 96.0000, 98.5000])

In [154]:
#Finds position in tensor with minimal value with argmin() -> returns index position
x.argmin()

tensor(0)

In [155]:
#Finds position in tensor with minimal value with argmin() -> returns index position
x.argmax()

tensor(39)

In [156]:
x[x.argmax()]

tensor(98.5000)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as original tensor
* Stacking - combine multiple tensors vstack(on top of each other) or hstack(side by side).
* Squeeze - removes all `1` dimensions from a tensor.
* Unsqueeze - add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a particular way.

In [161]:
#Create tensor
import torch
x = torch.arange(0, 10)
print(x)
print(x.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])


In [172]:
#Add an extra dimension   Stuff must add up
x_reshaped1 = x.reshape(1,10)
x_reshaped2 = x.reshape(5,2)
x_reshaped3 = x.reshape(10,1)

print(x_reshaped1)
print(x_reshaped1.shape)
print(x_reshaped2)
print(x_reshaped2.shape)
print(x_reshaped3)
print(x_reshaped3.shape)


tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
torch.Size([5, 2])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
torch.Size([10, 1])


In [175]:
# Change the View
z = x.view(1, 10)
z, z.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [185]:
#Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 4
z, x

(tensor([[4, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([4, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [183]:
#Stack Tensors on top of each other  (V-Stack)
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])