PyTorch 00

In [60]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Pytorch Version: " + torch.__version__)

Pytorch Version: 1.13.1


In [17]:
# scalar tensor
scalar = torch.tensor(7)
scalar

scalar.ndim #dimension


0

In [23]:
# Vector 
vector = torch.tensor([7.7])
print(vector)
print(vector.ndim)


tensor([7.7000])
1


In [61]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)

tensor([[ 7,  8],
        [ 9, 10]])
2


In [28]:
MATRIX[1]

tensor([ 9, 10])

In [30]:
MATRIX.shape

torch.Size([2, 2])

In [66]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 1],
                       [1, 1, 0],
                       [1, 1, 2]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 1],
         [1, 1, 0],
         [1, 1, 2]]])
3
torch.Size([1, 3, 3])


Creating Tensors

In [67]:
#Random Tensor
#Create a random tensor

#provide size
random_tensor = torch.rand(3, 7)
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor)


2
torch.Size([3, 7])
tensor([[0.4781, 0.8840, 0.3208, 0.1702, 0.6051, 0.6483, 0.4660],
        [0.0127, 0.2432, 0.4693, 0.5071, 0.3023, 0.8946, 0.5158],
        [0.8983, 0.9345, 0.5592, 0.4146, 0.6529, 0.8651, 0.6174]])


In [69]:
# Random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels
