PyTorch 00

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Pytorch Version: " + torch.__version__)

Pytorch Version: 1.13.1


In [2]:
# scalar tensor
scalar = torch.tensor(7)
scalar

scalar.ndim #dimension


0

In [311]:
# Vector 
vector = torch.tensor([7.7])
print(vector)
print(vector.ndim)


tensor([7.7000])
1


In [312]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)

tensor([[ 7,  8],
        [ 9, 10]])
2


In [313]:
MATRIX[1]

tensor([ 9, 10])

In [314]:
MATRIX.shape

torch.Size([2, 2])

In [315]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 1],
                       [1, 1, 0],
                       [1, 1, 2]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 1],
         [1, 1, 0],
         [1, 1, 2]]])
3
torch.Size([1, 3, 3])


Creating Tensors

In [316]:
#Random Tensor
#Create a random tensor

#provide size
random_tensor = torch.rand(3, 7)
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor)


2
torch.Size([3, 7])
tensor([[0.2970, 0.7513, 0.4894, 0.1067, 0.2661, 0.1986, 0.5087],
        [0.1936, 0.4431, 0.6121, 0.3399, 0.8969, 0.7082, 0.0395],
        [0.5143, 0.7273, 0.1270, 0.9565, 0.0248, 0.8383, 0.1274]])


In [317]:
# Random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels


Creating Random Tensor

In [318]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [319]:
oneTensor = torch.ones(size=(3,4))
oneTensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [320]:
nineRange = torch.arange(0,10)

Tensors Like

In [321]:
#Creatign Zeros-like
ten_zeros = torch.zeros_like(input=nineRange)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [322]:
#Flot 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                                dtype=None, # Data type
                                device="cpu", # What device is your tensor on
                                requires_grad=False) # Whether or not to track gradients with tensor
float_32_tensor


tensor([3., 6., 9.])

In [323]:
float_16_tensor = float_32_tensor.type(torch.float16)  # Casting to lower precision

In [324]:
#Multiplication accorss data types?
print(float_32_tensor * float_16_tensor)



tensor([ 9., 36., 81.])


In [325]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

### Getting information from Tensors

1. Tensors not right Data Type
2. Tensors not right shape
3. Tensors not on right device - For local AMD GPU machine, just use "cpu"  use "cuda" if NVIDIA Gpu used


In [326]:
# Find out details about some tensor
print(int_32_tensor)
print(f"Datatype of tensor:  {int_32_tensor.shape}")
print(f"Device tensor is on:  {int_32_tensor.device}")

tensor([3, 6, 9])
Datatype of tensor:  torch.Size([3])
Device tensor is on:  cpu


### Manipulating and Operating with tensors

Tensor Operations: 
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matric Mulitplication

In [327]:
# Tensor 1
tensor1 = torch.tensor([1, 2, 3])
tensor1 + 10  # adds 10 to each

tensor([11, 12, 13])

In [328]:
#Multiplication:    WORKS ELEMENT WISE
tensor1 * 10

tensor([10, 20, 30])

In [329]:
tensor1 - 10

tensor([-9, -8, -7])

### Matrix Multiplication

Two main ways of performing multiplication in machine learning and deep learning
1. Matrix Multiplication (dot product)
2. Element Wise multiplication


In [330]:
# Element Wise: 
print(tensor1, "*", tensor1)
print(f"EqualsL {tensor1 * tensor1}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
EqualsL tensor([1, 4, 9])


In [331]:
%%time
# Matrix Multiplication:  (DOT PRODUCT)
print(tensor1, "dot", tensor1)
print(torch.matmul(tensor1, int_32_tensor))

tensor([1, 2, 3]) dot tensor([1, 2, 3])
tensor(42)
Wall time: 1e+03 µs


In [332]:
#Tensors
tensor_A = torch.tensor([[1, 2],
                        [3, 6],
                        [8, 2]])
tensor_B = torch.tensor([[0, 1],
                        [4, 9],
                        [1, 3]])
#torch.mm is analagous to matmul
#torch.matmul(tensor_A, tensor_B)
tensor_BT = tensor_B.T
print(tensor_BT.shape)

# To fix shape issues, use transpose!
torch.matmul(tensor_A, tensor_BT)

torch.Size([2, 3])


tensor([[ 2, 22,  7],
        [ 6, 66, 21],
        [ 2, 50, 14]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [333]:
# Create a tensor
x = torch.arange(1,100,2.5)
x, x.dtype

(tensor([ 1.0000,  3.5000,  6.0000,  8.5000, 11.0000, 13.5000, 16.0000, 18.5000,
         21.0000, 23.5000, 26.0000, 28.5000, 31.0000, 33.5000, 36.0000, 38.5000,
         41.0000, 43.5000, 46.0000, 48.5000, 51.0000, 53.5000, 56.0000, 58.5000,
         61.0000, 63.5000, 66.0000, 68.5000, 71.0000, 73.5000, 76.0000, 78.5000,
         81.0000, 83.5000, 86.0000, 88.5000, 91.0000, 93.5000, 96.0000, 98.5000]),
 torch.float32)

In [334]:
#Find the min and max
print("Min: " + str(torch.min(x)))
print("Min: " + str(torch.max(x)))
x, x.dtype



Min: tensor(1.)
Min: tensor(98.5000)


(tensor([ 1.0000,  3.5000,  6.0000,  8.5000, 11.0000, 13.5000, 16.0000, 18.5000,
         21.0000, 23.5000, 26.0000, 28.5000, 31.0000, 33.5000, 36.0000, 38.5000,
         41.0000, 43.5000, 46.0000, 48.5000, 51.0000, 53.5000, 56.0000, 58.5000,
         61.0000, 63.5000, 66.0000, 68.5000, 71.0000, 73.5000, 76.0000, 78.5000,
         81.0000, 83.5000, 86.0000, 88.5000, 91.0000, 93.5000, 96.0000, 98.5000]),
 torch.float32)

In [335]:
#Find Mean - torch.mean() function will require a tensor of float32 datatype!
torch.mean(x.type(torch.float32))

tensor(49.7500)

## Finding Positional min and max

In [336]:
#reuse tensor x
x

tensor([ 1.0000,  3.5000,  6.0000,  8.5000, 11.0000, 13.5000, 16.0000, 18.5000,
        21.0000, 23.5000, 26.0000, 28.5000, 31.0000, 33.5000, 36.0000, 38.5000,
        41.0000, 43.5000, 46.0000, 48.5000, 51.0000, 53.5000, 56.0000, 58.5000,
        61.0000, 63.5000, 66.0000, 68.5000, 71.0000, 73.5000, 76.0000, 78.5000,
        81.0000, 83.5000, 86.0000, 88.5000, 91.0000, 93.5000, 96.0000, 98.5000])

In [337]:
#Finds position in tensor with minimal value with argmin() -> returns index position
x.argmin()

tensor(0)

In [338]:
#Finds position in tensor with minimal value with argmin() -> returns index position
x.argmax()

tensor(39)

In [339]:
x[x.argmax()]

tensor(98.5000)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as original tensor
* Stacking - combine multiple tensors vstack(on top of each other) or hstack(side by side).
* Squeeze - removes all `1` dimensions from a tensor.
* Unsqueeze - add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a particular way.

In [340]:
#Create tensor
import torch
x = torch.arange(0, 10)
print(x)
print(x.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])


In [341]:
#Add an extra dimension   Stuff must add up
x_reshaped1 = x.reshape(1,10)
x_reshaped2 = x.reshape(5,2)
x_reshaped3 = x.reshape(10,1)

print(x_reshaped1)
print(x_reshaped1.shape)
print(x_reshaped2)
print(x_reshaped2.shape)
print(x_reshaped3)
print(x_reshaped3.shape)


tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
torch.Size([5, 2])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
torch.Size([10, 1])


In [342]:
# Change the View
z = x.view(1, 10)
z, z.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [343]:
#Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 4
z, x

(tensor([[4, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([4, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [344]:
#Stack Tensors on top of each other  (V-Stack)
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[4, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [4, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [4, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [4, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [345]:
#Squeeze:    torch.squeese() - removes all 1 dimensions from a target tensor
# 1 dimension containers act like removable containers .... sort of ...
tn = torch.rand(size=(5,2,1))
tnSqueezed = torch.squeeze(tn)   # removes "1" dimensions.
print(f"Previous tensor: {tn}")
print(f"Squeezed tensor: {tnSqueezed}")

Previous tensor: tensor([[[0.8185],
         [0.3964]],

        [[0.9152],
         [0.8344]],

        [[0.8817],
         [0.0132]],

        [[0.4247],
         [0.4350]],

        [[0.4850],
         [0.5960]]])
Squeezed tensor: tensor([[0.8185, 0.3964],
        [0.9152, 0.8344],
        [0.8817, 0.0132],
        [0.4247, 0.4350],
        [0.4850, 0.5960]])


In [346]:
#torch.unsqueeze()  -  adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target tensor: {tnSqueezed}")
print(f"Previous shape: {tnSqueezed.shape}")

# Add an additional dimension with unsqueeze
# torch.unsqueeze(TARGET_TENSOR, DIMENSION TO "WRAP" WITH SINGLE DIMENSION)
tnUnsqueezed = torch.unsqueeze(tnSqueezed, 2)
print(f"\n New UNSQUEEZED tensor: {tnUnsqueezed}")
print(f"New (original tn shape) shape: {tnUnsqueezed.shape}")


Previous target tensor: tensor([[0.8185, 0.3964],
        [0.9152, 0.8344],
        [0.8817, 0.0132],
        [0.4247, 0.4350],
        [0.4850, 0.5960]])
Previous shape: torch.Size([5, 2])

 New UNSQUEEZED tensor: tensor([[[0.8185],
         [0.3964]],

        [[0.9152],
         [0.8344]],

        [[0.8817],
         [0.0132]],

        [[0.4247],
         [0.4350]],

        [[0.4850],
         [0.5960]]])
New (original tn shape) shape: torch.Size([5, 2, 1])


In [347]:
# torch.permute()  - Returns a view of the original tensor `input` with its dimensions permuted
v = torch.rand(size=(224,224,3))   # good way to represent images  224 x 224 x RGB
v

tensor([[[5.1906e-01, 4.0610e-01, 9.0105e-01],
         [8.0206e-01, 1.1850e-01, 5.7680e-01],
         [2.1473e-01, 8.8326e-01, 3.9759e-01],
         ...,
         [2.6059e-01, 5.6435e-02, 6.8631e-01],
         [7.3182e-01, 8.0589e-01, 6.7250e-01],
         [4.3772e-01, 1.7333e-01, 7.1856e-01]],

        [[9.1602e-02, 3.9481e-01, 4.0269e-01],
         [8.9518e-01, 6.5881e-01, 3.0708e-02],
         [9.7853e-01, 9.4710e-01, 2.4458e-01],
         ...,
         [6.9098e-01, 8.1801e-01, 1.1460e-03],
         [5.8473e-01, 2.9705e-01, 6.7049e-01],
         [4.3270e-01, 9.5215e-01, 4.2599e-01]],

        [[5.4933e-01, 4.9004e-01, 7.2240e-01],
         [4.0232e-01, 9.2364e-01, 5.3077e-01],
         [3.8115e-01, 4.3802e-01, 6.7846e-01],
         ...,
         [8.6409e-01, 5.2914e-01, 1.8092e-01],
         [7.6402e-01, 9.8428e-01, 5.6620e-01],
         [6.9923e-01, 9.2798e-01, 3.0902e-01]],

        ...,

        [[2.2902e-01, 1.6096e-02, 4.4225e-01],
         [7.7782e-01, 2.4841e-02, 9.8647e-01]

In [348]:
# permute the original rensor to rearrange the axis or dim order
vPermuted = v.permute(2,0,1)  # Shifts axis 0->1, 1->2, 2->0  
print("prev shape: " + str(v.shape))
print("permuted shape: " + str(vPermuted.shape))
# [R/G/B, height, width]    3 sheets, each of RGorB insterad of 224x224 pixles of RGB data

# BOTH WILL SHARE THE SAME PLACE IN MEMORY DESPITE BEING DIFFERENT VIEWS!
 

prev shape: torch.Size([224, 224, 3])
permuted shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)
Indexing with Pytorch is similar to indexing with NumPy

In [349]:
#Create a Tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [350]:
#Let's index ton the new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [351]:
#Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [352]:
#Let's index on the most inner bracket (last dimension)
x[0][1][2]

tensor(6)

In [353]:
#get all values of 0th and 1st diensions by only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [354]:
x[:, :, :]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [355]:
x[0, 1, 1]

tensor(5)

In [356]:
# Get index 0 of 0th and 1st dimension and all vlaues of 2nd dimension.
x[0,0,:]   #Get's all remaining values in last dimension

tensor([1, 2, 3])

### Pytorch Tensors vs Numpy data
Numpy is popular for scientific python things.
PyTorch can work with it!
* Data in NumPy, want in PyTorch - > `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [357]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(array)
print(tensor)

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [358]:
#Change the value of array, what will hapen to `tensor`?
array = array + 1   #Only array will be chagned, new tensor will not change!
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
#Tensor to NumPy Array
tensor = torch.ones(23)
numpyTensor = tensor.numpy()
tensor, numpyTensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducility (trying to take random out of Random)

To reduce the randomness in neural networks and PyTorch comes the concept of random seed.
"Psuedorandomness"

In [4]:
torch.rand(3,3)

tensor([[0.3260, 0.2897, 0.3466],
        [0.6945, 0.6382, 0.8429],
        [0.0186, 0.4801, 0.1666]])

In [5]:
#Create two random tensors
randomTensorA = torch.rand(4,3)
randomTensorB = torch.rand(4,3)
print(randomTensorA == randomTensorB)



tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])


In [6]:
# Create random, yet reproducible tensors
import torch
#First, set a random SEED
RANDOM_SEED = 231
torch.manual_seed(RANDOM_SEED)   # MANUAL SEED WILL GENERALLY WORK FOR ONE
randomTensorC = torch.rand(7,2)
torch.manual_seed(RANDOM_SEED)
randomTensorD = torch.rand(7,2)
print(randomTensorC == randomTensorD)

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])


## Running Tensors and Pytorch objexts on the GPUs (and making faster computations)

### 1. Getting a GPU:
1. Use google colab
2. Local
3. Cloud computing setup

CHECK FOR GPU in COLAB

In [7]:
#Chekc for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [8]:
#Setup device agnostic code (i.e use GPU if possible)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.tensor([1,2,3])
device

'cpu'

In [9]:
#Count number of devices?
torch.cuda.device_count()

0

In [10]:
#Move tensor to GPU (if available)
tensor_on_target = tensor.to(device)
tensor_on_target, tensor_on_target.device

(tensor([1, 2, 3]), device(type='cpu'))

## Moving tensors back to the CPU


In [11]:
# If tensor is on GPU, can't trandorm it to NumpPy
# To fixc the GPU tensor with NumPy issue, we can first set it to the CPU
tensorOnCpu = tensor.to(device="cpu")
tensor.numpy()   # able to convert tensor to numpy data when it is computed by the CPU!

array([1, 2, 3], dtype=int64)